name: AxVaults
version: '${project.version}'
main: com.artillexstudios.axvaults.AxVaults
api-version: '1.18'
folia-supported: true

softdepend:
  - PlaceholderAPI

permissions:
  axvaults.vault.1:
    default: op
  axvaults.selector:
    default: op
  axvaults.openremote:
    default: op
  axvaults.itempicker:
    default: op
  axvaults.admin.*:
    default: op
  axvaults.admin.reload:
    default: op
  axvaults.admin.forceopen:
    default: op
  axvaults.admin.view:
    default: op
  axvaults.admin.delete:
    default: op
  axvaults.admin.set:
    default: op
  axvaults.admin.converter:
    default: op